---

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ticketsale_db
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        properties:
            hibernate: org.hibernate.dialect.MySQLDialect

...